Algoritmo "Exercício12-Contagem Regressiva"

//Crie um algoritmo que exiba os números de 10 até 1 e
//no final escreva "Feliz Ano novo!".

Var
// Seção de Declarações das variáveis
   i: inteiro
   
Inicio
// Seção de comandos, procedimentos, funções, operador
 // Contagem de 10 até 1 voltando de 1 em 1
   para i de 10 ate 1 passo -1 faca
      escreval(i)
   fimpara

   escreval("")
   escreval("Feliz Ano Novo!")

fimalgoritmo
