Algoritmo "exercicio1-DobroDeUmNúmero"

// Crie um algoritmo que leia um número inteiro e exiba o seu dobro.
Var
// Seção de Declarações das variáveis 

	numero, dobro : inteiro

Inicio
// Seção de comandos, procedimentos, funções, operador
	escreval ("Digite um numero: ")
	leia(numero)

	dobro <- numero*2
	escreval ("Você digitou o numero: ",numero)
	escreval ("o dobro dele é ", dobro)

fimalgoritmo
